DATA    SEGMENT
	HEX_NUM  DB   0,1,2,3,4,5,6,7,8,9,0AH,0BH,0CH,0DH,0EH,0FH
	TABLE	 DB   '0123456789ABCDEF'
DATA    ENDS
CODE   SEGMENT
        ASSUME CS:CODE,DS:DATA
START: 	MOV AX,DATA
        MOV DS,AX
        
		MOV CX,16;计数器初值16
		MOV BX,OFFSET TABLE
		MOV SI,OFFSET HEX_NUM
     L:	MOV AL,[SI]
		XLAT TABLE		;换码DS:[BX+AL]→AL 查表换码
		MOV DL,AL
		MOV AH,02H		;显示输出单字符
		INT 21H
		MOV DL,' '      ;显示空格
		INT 21H
		INC SI			;SI = SI + 1
		LOOP L
		
		MOV AH,4CH
    	INT 21H
CODE  ENDS
END START				
